version: '3'

services:
  db:
    container_name: core-api-db
    image: postgres:13
    environment:
      POSTGRES_DB: core-api-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  pgadmin_root_prefs:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local